-- title = StupidTRPG
-- saveid = stupidtrpg
-- author = Chris Moore
-- description = just a stupid tactical rpg demo
-- editTilemap.draw16Sprites = true
-- editBrushmap.draw16Sprites = true
-- editTilemap.sheetBlobIndex = 1
-- editBrushmap.sheetBlobIndex = 1
-- editMesh3D.sheetBlobIndex = 1
-- editVoxelmap.sheetBlobIndex = 1

--#include main.lua
